production:
  guild:
    id: "500233731836084225"
  channel:
    default:
      id: "500233731836084229"
    overview:
      id: "513476424179384330"
    rules:
      id: "500254672318365696"
  roles:
    - name: "Administrator"
      role:
        id: "500234978429501440"
    - name: "BotAdmin"
      role:
        id: "503584632340480021"
    - name: "Moderatoren"
      role:
        id: "500250774241017878"
    - name: "Lineare Algebra"
      emoji:
        id: "513462547333251072"
      role:
        id: "513472851731415050"
      channel:
        id: "500249889230290944"
    - name: "Lineare Algebra 2"
      emoji:
        id: "566327123350913055"
      role:
        id: "566261479142064129"
      channel:
        id: "565825852730900480"
    - name: "Experimentalphysik"
      emoji:
        id: "513462516379025419"
      role:
        id: "513473710053916672"
      channel:
        id: "500249796137844736"
    - name: "Experimentalphysik 2"
      emoji:
        id: "566327021894893576"
      role:
        id: "566260752600793113"
      channel:
        id: "565651160455839764"
    - name: "Experimentalphysik 3"
      emoji:
        id: "631080038824935444"
      role:
        id: "629706460711878689"
      channel:
        id: "629704498583175178"
    - name: "Theoretische Physik"
      emoji:
        id: "513462569126723587"
      role:
        id: "513473543221280779"
      channel:
        id: "500249851775156224"
    - name: "Theoretische Physik 2"
      emoji:
        id: "566327086801879042"
      role:
        id: "566261252838522880"
      channel:
        id: "565651703114760215"
    - name: "Theoretische Physik 3"
      emoji:
        id: "631079858293964801"
      role:
        id: "629706063360294932"
      channel:
        id: "629704725520056340"
    - name: "Analysis"
      emoji:
        id: "513462472376713250"
      role:
        id: "513473131843813389"
      channel:
        id: "500249914320748544"
    - name: "Analysis 2"
      emoji:
        id: "566327160483217408"
      role:
        id: "566261560809619477"
      channel:
        id: "565652539882602503"
    - name: "Höhere Analysis"
      emoji:
        id: "631080234510319646"
      role:
        id: "629706077226926090"
      channel:
        id: "629708753318707282"
    - name: "Höhere Mathematik"
      emoji:
        id: "566327057764843540"
      role:
        id: "566261757878730752"
      channel:
        id: "565652286383063062"
    - name: "Höhere Mathematik 3"
      emoji:
        id: "631080141375799356"
      role:
        id: "629706467049603107"
      channel:
        id: "629708318432034879"
    - name: "Astronomie"
      emoji:
        id: "631080084828061707"
      role:
        id: "629706910890721280"
      channel:
        id: "629709041085710347"
    - name: "Praktische Informatik"
      emoji:
        id: "634501134270332948"
      role:
        id: "634456581081399316"
      channel:
        id: "634264225107410955"
    - name: "Mathe"
      emoji:
        id: "513462751507644416"
      role:
        id: "513478232998150144"
    - name: "Physik"
      emoji:
        id: "513462837603991553"
      role:
        id: "500235278577958912"
    - name: "Angewandte Informatik"
      emoji:
        id: "513462797338673238"
      role:
        id: "501827079235698688"
development:
  guild:
    id: "506552477542383625"
  channel:
    default:
      id: "506552477542383627"
    rules:
      id: "506558801323753472"
    overview:
      id: "506560778065805332"
    dev:
      id: "512362690685960204"
  roles:
    - name: "Superuser"
      role:
        id: "512362211377676315"
    - name: "Lineare Algebra"
      emoji:
        id: "506571716647059487"
      role:
        id: "506567059669385226"
      channel:
        id: "506567708813295616"
    - name: "Lineare Algebra 2"
      emoji:
        id: "566258076953608202"
      role:
        id: "566255156488830996"
      channel:
        id: "566261054447943686"
    - name: "Experimentalphysik"
      emoji:
        id: "506570343041990659"
      role:
        id: "506567163587461130"
      channel:
        id: "506567537086038016"
    - name: "Experimentalphysik 2"
      emoji:
        id: "566257576379940867"
      role:
        id: "566255534165196802"
      channel:
        id: "566261166498906133"
    - name: "Theoretische Physik"
      emoji:
        id: "506570912250724356"
      role:
        id: "506567161544966165"
      channel:
        id: "506567677431513099"
    - name: "Theoretische Physik 2"
      emoji:
        id: "566258679134027788"
      role:
        id: "566255396973576202"
      channel:
        id: "566261139441188886"
    - name: "Analysis"
      emoji:
        id: "512764610949021697"
      role:
        id: "512765937276026891"
      channel:
        id: "512767313187962882"
    - name: "Analysis 2"
      emoji:
        id: "566256974564425778"
      role:
        id: "566255648644530196"
      channel:
        id: "566261187705307137"
    - name: "Höhere Mathematik"
      emoji:
        id:  "566070778546618377"
      role:
        id: "566067857784307749"
    - name: "Mathe"
      emoji:
        id: "512764716582567957"
      role:
        id: "512766037549121545"
    - name: "Physik"
      emoji:
        id: "512765168292200452"
      role:
        id: "512766040837455883"
    - name: "Informatik"
      emoji:
        id: "512764684173312027"
      role:
        id: "512766009413730315"